sudo: false
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
branches:
  except:
    - /^WIP-.*$/
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install tox-travis
script:
  - tox
matrix:
  allow_failures:
    - python: "pypy3"
