language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - echo "no dependencies to install"
before_script:
  - git config --global user.email "foo@example.com"
  - git config --global user.name "foo"
script:
  - python test/test_git.py
